FROM rayproject/ray
EXPOSE 8000

# pip dependencies
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt --no-cache-dir

# runtime
COPY ../scripts scripts
CMD ["python", "/scripts/deploy.py"]

